services:
  collaboration-service:
    build: .
    container_name: collaboration-service
    ports:
      - "3004:3004"    # API and WebSocket port
    volumes:
      - .:/app         # Mount source code for hot reload
      - /app/node_modules  # Don't overwrite node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/collab
      - JWT_SECRET=${JWT_SECRET} # Use environment variable for JWT secret
      - LOG_LEVEL=debug
    depends_on:
      - mongo
    restart: unless-stopped
  
  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo-data:
